### ISSUE TITLE
Runtime Error CUDA/Torch

### ISSUE THREAD

**Issue by ddkats** [MAC-VO/MAC-VO#24]
Hi @haleqiu  

Congrats on your excellent work! I'm very interested in testing it as part of a larger mapping framework using ZED cameras.

Following your instructions step by step using the Docker setup, I encountered a runtime **CUDA/Torch issue**. Do you know what might be causing this? I’ve tested it on both Ubuntu 20 and 22 with CUDA versions 11.4, 11.7, and 12.2, respectively. Should I switch the host to CUDA 12.4 to run it successfully? Have you ever tested it with earlier CUDA versions?

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

The entire log of the error is this:
```
macvo@8abe8508773e:~/workspace$ sudo python3 MACVO.py --odom Config/Experiment/MACVO/MACVO_Performant.yaml --data Config/Sequence/TartanAir_example.yaml
[08:45:46] INFO     PID 67 generated new fontManager                            font_manager.py:1639
Initialized new /root/.evo/settings.json
fatal: detected dubious ownership in repository at '/home/macvo/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/macvo/workspace
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:174: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/macvo/workspace/MACVO.py", line 140, in <module>
    system = MACVO[StereoFrame].from_config(asNamespace(exp_space.config))
  File "/home/macvo/workspace/Odometry/MACVO.py", line 84, in from_config
    Frontend            = Module.IFrontend.instantiate(odomcfg.frontend.type, odomcfg.frontend.args)
  File "/home/macvo/workspace/Utility/Extensions/SubclassRegistry.py", line 26, in instantiate
    return cls.get_class(type)(*args, **kwargs)
  File "/home/macvo/workspace/Module/Frontend/Frontend.py", line 270, in __init__
    super().__init__(config)
  File "/home/macvo/workspace/Module/Frontend/Frontend.py", line 172, in __init__
    ckpt  = torch.load(self.config.weight, map_location=self.config.device, weights_only=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1516, in load
    return _load(
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 2114, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.10/dist-packages/torch/_weights_only_unpickler.py", line 532, in load
    self.append(self.persistent_load(pid))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 2078, in persistent_load
    typed_storage = load_tensor(
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 2044, in load_tensor
    wrap_storage = restore_location(storage, location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1854, in restore_location
    return default_restore_location(storage, map_location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 698, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 636, in _deserialize
    device = _validate_device(location, backend_name)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 605, in _validate_device
    raise RuntimeError(
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

Thanks!

**Comment by MarkChenYutian** [comment]
Hi, our implementation should not be strongly bound to a CUDA runtime since we haven't written any CUDA kernels (yet). From the exception, it seems like `torch.cuda.is_available()` is `False` in your Docker environment. Did you install the Nvidia Container Runtime on your machine?

Our code *probably* works in a CPU-only environment (runs very slowly, though). You can try CPU-only mode by switching `device` to `cpu` in `MACVO_Performant.yaml`.

**Comment by MarkChenYutian** [comment]
Hi @ddkats 

I still suspect there is a configuration problem with the docker container, since the last line of previous exception:

```
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False.
If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

We are developing using a minimal PyTorch version of 2.4, which depends on CUDA runtime 12.4+. Our docker file also uses CUDA 12.4 for that reason.

https://github.com/MAC-VO/MAC-VO/blob/b72acaa3c4c64c05f04847263c8ea1defc4fd5ed/Docker/Dockerfile#L1

Since the CUDA calls in Docker will be "forwarded" to the host machine CUDA (image from https://github.com/NVIDIA/nvidia-container-toolkit), I would recommend upgrading the CUDA runtime on Host machine, if possible and see if the `nvidia-smi` is working in Docker container. (`nvcc` in container may still show version while `CUDA` is actually not usable).

![](https://cloud.githubusercontent.com/assets/3028125/12213714/5b208976-b632-11e5-8406-38d379ec46aa.png)

As for the CPU-only runtime, yes the CUDA graph acceleration only works on CUDA GPU. Please change `type: CUDAGraph_FlowFormerCovFrontend` in the config file (Under `Odometry.Frontend`) to `type: FlowFormerCovFrontend` to use vanilla network.

**Comment by ddkats** [comment]
Hi @MarkChenYutian 

Thanks for your time and your efforts to debug this issue, I really appreciate it.

The nvidia-smi from inside the docker env works just fine. Also I updated the nvidia-toolkit in the host pc and it now runs toolkit 12.4. So the host has nvidia-smi=12.2 (can't update the drivers) and nvcc=12.4, the error is the same after this update. 

Regarding the CPU-mode even after setting the ```Odometry.Frontend``` to type: ```FlowFormerCovFrontend``` + ```device cpu```, there is still CUDA-related errors. 

The ```nvidia-smi``` from inside the Docker environment works just fine. I also updated the NVIDIA toolkit on the host PC, which now runs Toolkit 12.4. So, the host has ```nvidia-smi = 12.2``` and ```nvcc = 12.4```. The error remains the same after this update (error (1)).

Regarding CPU mode, even after setting the ```Odometry.Frontend``` to type: ```FlowFormerCovFrontend``` + ```device: cpu```, there are still CUDA-related errors (error (2)).

The full logs for both of error (1) and error (2) are outlined below, respectively.

error (1)
```
macvo@a95aff6f37a9:~$ nvidia-smi
Wed Jul  9 07:16:36 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.4     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 ...    Off | 00000000:08:00.0  On |                  N/A |
|  0%   53C    P8              12W / 250W |    571MiB /  8192MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

macvo@63fe2dc8f94d:~/workspace$ sudo python3 MACVO.py --odom Config/Experiment/MACVO/MACVO_Performant.yaml --data Config/Sequence/TartanAir_example.yaml
[09:29:40] INFO     PID 65 generated new fontManager                                                                     font_manager.py:1639
Initialized new /root/.evo/settings.json
fatal: detected dubious ownership in repository at '/home/macvo/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/macvo/workspace
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:174: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/home/macvo/workspace/MACVO.py", line 140, in <module>
    system = MACVO[StereoFrame].from_config(asNamespace(exp_space.config))
  File "/home/macvo/workspace/Odometry/MACVO.py", line 84, in from_config
    Frontend            = Module.IFrontend.instantiate(odomcfg.frontend.type, odomcfg.frontend.args)
  File "/home/macvo/workspace/Utility/Extensions/SubclassRegistry.py", line 26, in instantiate
    return cls.get_class(type)(*args, **kwargs)
  File "/home/macvo/workspace/Module/Frontend/Frontend.py", line 270, in __init__
    super().__init__(config)
  File "/home/macvo/workspace/Module/Frontend/Frontend.py", line 172, in __init__
    ckpt  = torch.load(self.config.weight, map_location=self.config.device, weights_only=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1516, in load
    return _load(
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 2114, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.10/dist-packages/torch/_weights_only_unpickler.py", line 532, in load
    self.append(self.persistent_load(pid))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 2078, in persistent_load
    typed_storage = load_tensor(
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 2044, in load_tensor
    wrap_storage = restore_location(storage, location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1854, in restore_location
    return default_restore_location(storage, map_location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 698, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 636, in _deserialize
    device = _validate_device(location, backend_name)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 605, in _validate_device
    raise RuntimeError(
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

error (2)
```
macvo@235c0f0056a9:~/workspace$ sudo python3 MACVO.py --odom Config/Experiment/MACVO/MACVO_Performant.yaml --data Config/Sequence/TartanAir_example.yaml
fatal: detected dubious ownership in repository at '/home/macvo/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/macvo/workspace
╭─ Odometry Covariance ───────────────╮ ╭─ Odometry Modules ──────────────────────────╮
│ DepthEstimator cov: True            │ │ Optimizer       -'TwoFrame_PGO'             │
│ MatchEstimator cov: True            │ │ Frontend        -'FlowFormerCovFrontend'    │
│ Observation cov:    MatchCovariance │ │ MotionEstimator -'StaticMotionModel'        │
╰─────────────────────────────────────╯ │ KeypointSelector-'CovAwareSelector_NoDepth' │
                                        │ MappointSelector-'MappingPointSelector'     │
                                        │ OutlierFilter   -'CovarianceSanityFilter'   │
                                        │ MapRefiner      -'MotionInterpolate'        │
                                        ╰─────────────────────────────────────────────╯
  0%|                                                            | 0/1274 [00:00<?, ?it/s][07:24:11] INFO     PID 251 OptimizationParallelWorker started                      Interface.py:250
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:174: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:174: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
VisualMap(#frame=1, #point=0, #map=0), VRAM=N/A:   0%| | 1/1274 [00:11<3:56:16, 11.14s/it]Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/macvo/workspace/Module/Optimization/Interface.py", line 263, in IOptimizerParallelWorker
    context, graph_res = optimize(context, graph_args_local)
  File "/home/macvo/workspace/Module/Optimization/TwoFramePGO/Optimizer.py", line 83, in _optimize
    with Timer.CPUTimingContext("TwoframePGO"), Timer.GPUTimingContext("TwoframePGO", torch.cuda.current_stream()):
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 1065, in current_stream
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
❌VisualMap(#frame=2, #point=200, #map=2000), VRAM=N/A:   0%| | 2/1274 [00:46<8:11:17, 23.
Traceback (most recent call last):
  File "/home/macvo/workspace/Odometry/Interface.py", line 36, in receive_frames
    self.run(frame)
  File "/home/macvo/workspace/Utility/Timer.py", line 29, in wrapped
    if not cls.ACTIVE: return func(*args, **kwargs)
  File "/home/macvo/workspace/Utility/Timer.py", line 46, in wrapped
    if not cls.ACTIVE: return func(*args, **kwargs)
  File "/home/macvo/workspace/Odometry/MACVO.py", line 368, in run
    self.run_pair(self.prev_keyframe[0], frame)
  File "/home/macvo/workspace/Odometry/MACVO.py", line 187, in run_pair
    self.Optimizer.write_map(self.graph)
  File "/home/macvo/workspace/Module/Optimization/Interface.py", line 227, in write_map
    graph_res_local = self.__get_output_parallel()
  File "/home/macvo/workspace/Module/Optimization/Interface.py", line 147, in __get_output_parallel
    assert self.child_proc and self.child_proc.is_alive()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/macvo/workspace/MACVO.py", line 141, in <module>
    system.receive_frames(sequence, exp_space, on_frame_finished=onFrameFinished)
  File "/home/macvo/workspace/Odometry/Interface.py", line 67, in receive_frames
    self.terminate()
  File "/home/macvo/workspace/Odometry/MACVO.py", line 376, in terminate
    self.Optimizer.write_map(self.graph)
  File "/home/macvo/workspace/Module/Optimization/Interface.py", line 227, in write_map
    graph_res_local = self.__get_output_parallel()
  File "/home/macvo/workspace/Module/Optimization/Interface.py", line 147, in __get_output_parallel
    assert self.child_proc and self.child_proc.is_alive()
AssertionError
macvo@235c0f0056a9:~/workspace$ 
```

**Comment by ddkats** [comment]
Hi @LVIC11 , no I didn't solve the issue

**Comment by LVIC11** [comment]
@ddkats thanks for reply!i have solved it through updating  nvidia-drivers,maybe it works.:)

**Comment by ddkats** [comment]
@LVIC11 Do you mean the drivers themselves or just the NVIDIA toolkit? In other words, did you change the version shown by nvidia-smi (drivers) or by nvcc -V (toolkit)? 

Also, which drivers are you using? I’m on 12.2 for both the drivers-toolkit.

**Comment by LVIC11** [comment]
@ddkats 

<img width="849" height="456" alt="Image" src="https://github.com/user-attachments/assets/0a44c5cc-42f2-4f9d-b6e3-486f7a1d6e5f" />

**Comment by LVIC11** [comment]
@ddkats If you have any questions,plz send me to 2208348810@qq.com :)

**Comment by LVIC11** [comment]
@ddkats Yes,i am on 12.4 for  both the drivers-toolkit.You should update the Driver Version first,which limits the CUDA MAX Version.I notice that you update the CUDA to 12.4.However,the nvidia-smi is still 12.2.It may be 12.2 in fact.You can try the below code to test it.

<img width="490" height="156" alt="Image" src="https://github.com/user-attachments/assets/f4d5d31b-3e92-4be1-a67d-937cf7861a6d" />
